// Code generated by protoc-gen-go from "example_ae/whoami/whoami.proto"
// DO NOT EDIT!

package whoami

import proto "code.google.com/p/goprotobuf/proto"
import "math"

import "net"
import "net/rpc"
import "github.com/kylelemons/go-rpcgen/codec"
import "net/url"
import "net/http"
import "github.com/kylelemons/go-rpcgen/webrpc"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Empty struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *Empty) Reset()         { *this = Empty{} }
func (this *Empty) String() string { return proto.CompactTextString(this) }

type YouAre struct {
	IpAddr           *string `protobuf:"bytes,1,req,name=ip_addr" json:"ip_addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *YouAre) Reset()         { *this = YouAre{} }
func (this *YouAre) String() string { return proto.CompactTextString(this) }

func init() {
}

// WhoamiService is an interface satisfied by the generated client and
// which must be implemented by the object wrapped by the server.
type WhoamiService interface {
	Whoami(in *Empty, out *YouAre) error
}

// internal wrapper for type-safe RPC calling
type rpcWhoamiServiceClient struct {
	*rpc.Client
}

func (this rpcWhoamiServiceClient) Whoami(in *Empty, out *YouAre) error {
	return this.Call("WhoamiService.Whoami", in, out)
}

// NewWhoamiServiceClient returns an *rpc.Client wrapper for calling the methods of
// WhoamiService remotely.
func NewWhoamiServiceClient(conn net.Conn) WhoamiService {
	return rpcWhoamiServiceClient{rpc.NewClientWithCodec(codec.NewClientCodec(conn))}
}

// ServeWhoamiService serves the given WhoamiService backend implementation on conn.
func ServeWhoamiService(conn net.Conn, backend WhoamiService) error {
	srv := rpc.NewServer()
	if err := srv.RegisterName("WhoamiService", backend); err != nil {
		return err
	}
	srv.ServeCodec(codec.NewServerCodec(conn))
	return nil
}

// DialWhoamiService returns a WhoamiService for calling the WhoamiService servince at addr (TCP).
func DialWhoamiService(addr string) (WhoamiService, error) {
	conn, err := net.Dial("tcp", addr)
	if err != nil {
		return nil, err
	}
	return NewWhoamiServiceClient(conn), nil
}

// ListenAndServeWhoamiService serves the given WhoamiService backend implementation
// on all connections accepted as a result of listening on addr (TCP).
func ListenAndServeWhoamiService(addr string, backend WhoamiService) error {
	clients, err := net.Listen("tcp", addr)
	if err != nil {
		return err
	}
	srv := rpc.NewServer()
	if err := srv.RegisterName("WhoamiService", backend); err != nil {
		return err
	}
	for {
		conn, err := clients.Accept()
		if err != nil {
			return err
		}
		go srv.ServeCodec(codec.NewServerCodec(conn))
	}
	panic("unreachable")
}

// WhoamiServiceWeb is the web-based RPC version of the interface which
// must be implemented by the object wrapped by the webrpc server.
type WhoamiServiceWeb interface {
	Whoami(r *http.Request, in *Empty, out *YouAre) error
}

// internal wrapper for type-safe webrpc calling
type rpcWhoamiServiceWebClient struct {
	remote   *url.URL
	protocol webrpc.Protocol
}

func (this rpcWhoamiServiceWebClient) Whoami(in *Empty, out *YouAre) error {
	return webrpc.Post(this.protocol, this.remote, "/WhoamiService/Whoami", in, out)
}

// Register a WhoamiServiceWeb implementation with the given webrpc ServeMux.
// If mux is nil, the default webrpc.ServeMux is used.
func RegisterWhoamiServiceWeb(this WhoamiServiceWeb, mux webrpc.ServeMux) error {
	if mux == nil {
		mux = webrpc.DefaultServeMux
	}
	if err := mux.Handle("/WhoamiService/Whoami", func(c *webrpc.Call) error {
		in, out := new(Empty), new(YouAre)
		if err := c.ReadRequest(in); err != nil {
			return err
		}
		if err := this.Whoami(c.Request, in, out); err != nil {
			return err
		}
		return c.WriteResponse(out)
	}); err != nil {
		return err
	}
	return nil
}

// NewWhoamiServiceWebClient returns a webrpc wrapper for calling the methods of WhoamiService
// remotely via the web.  The remote URL is the base URL of the webrpc server.
func NewWhoamiServiceWebClient(pro webrpc.Protocol, remote *url.URL) WhoamiService {
	return rpcWhoamiServiceWebClient{remote, pro}
}
