// +build !appengine

// Code generated by protoc-gen-go.
// source: whoami/whoami.proto
// DO NOT EDIT!

/*
Package whoami is a generated protocol buffer package.

It is generated from these files:
	whoami/whoami.proto

It has these top-level messages:
	Empty
	YouAre
*/
package whoami

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Empty struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}

type YouAre struct {
	IpAddr           *string `protobuf:"bytes,1,req,name=ip_addr" json:"ip_addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *YouAre) Reset()         { *m = YouAre{} }
func (m *YouAre) String() string { return proto.CompactTextString(m) }
func (*YouAre) ProtoMessage()    {}

func (m *YouAre) GetIpAddr() string {
	if m != nil && m.IpAddr != nil {
		return *m.IpAddr
	}
	return ""
}

func init() {
}
