// Code generated by protoc-gen-go from "protoc-gen-go/testdata/service.proto"
// DO NOT EDIT!

package svc

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Args struct {
	A                *string `protobuf:"bytes,1,req,name=a" json:"a,omitempty"`
	B                *string `protobuf:"bytes,2,req,name=b" json:"b,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Args) Reset()         { *this = Args{} }
func (this *Args) String() string { return proto.CompactTextString(this) }

type Return struct {
	C                *string `protobuf:"bytes,1,req,name=c" json:"c,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Return) Reset()         { *this = Return{} }
func (this *Return) String() string { return proto.CompactTextString(this) }

func init() {
}
