// Code generated by protoc-gen-go from "examples/echo/echoservice/echoservice.proto"
// DO NOT EDIT!

package echoservice

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Payload struct {
	Message          *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Payload) Reset()         { *this = Payload{} }
func (this *Payload) String() string { return proto.CompactTextString(this) }

func init() {
}
