// Code generated by protoc-gen-go.
// source: plugin/wire/wire.proto
// DO NOT EDIT!

package wire

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Header struct {
	Method           *string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Seq              *uint64 `protobuf:"varint,2,opt,name=seq" json:"seq,omitempty"`
	Error            *string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Header) Reset()         { *this = Header{} }
func (this *Header) String() string { return proto.CompactTextString(this) }
func (*Header) ProtoMessage()       {}

func (this *Header) GetMethod() string {
	if this != nil && this.Method != nil {
		return *this.Method
	}
	return ""
}

func (this *Header) GetSeq() uint64 {
	if this != nil && this.Seq != nil {
		return *this.Seq
	}
	return 0
}

func (this *Header) GetError() string {
	if this != nil && this.Error != nil {
		return *this.Error
	}
	return ""
}

func init() {
}
