// Code generated by protoc-gen-go from "services/wire/wire.proto"
// DO NOT EDIT!

package wire

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Header struct {
	Method           *string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Seq              *uint64 `protobuf:"varint,2,opt,name=seq" json:"seq,omitempty"`
	Error            *string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Header) Reset()         { *this = Header{} }
func (this *Header) String() string { return proto.CompactTextString(this) }

func init() {
}
